# Generated by Django 2.1.2 on 2018-10-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NesTag',
            new_name='NewTag',
        ),
    ]
