# Generated by Django 2.1.2 on 2018-10-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='tag',
        ),
    ]
